apiVersion: "v1"
kind: "Service"
metadata:
  name: "sample-app1-service"
  labels:
    app: "sample-app1"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "sample-app1"
  type: "LoadBalancer"
  loadBalancerIP: ""
